variables: variables-peliculas.yml
tasks:
  watchlist:
    priority: 1
    trakt_list:
      account: gacomun@gmail.com
      list: peliculas-descarga
      type: movies
      strip_dates: yes
    accept_all: yes
#    seen: local  # We don't want accepted movies on this feed to affect actual download feed
    list_add:
      - movie_list: pelidescarga  # you can call this whatever you want
    tmdb_lookup:
      language: es
  # task that automatically downloads movies from the movie_list
  movies search:
    trakt_lookup: yes  # can also use imdb_lookup or tmdb_lookup
    priority: 10 # run after the movie queue fill task
    discover:
      what:
        - movie_list: pelidescarga
      from:
        - descargas2020: yes
      #interval: 1 days
#    torrent_alive: 10 # Will reject results with less than 10 seeds
    quality: hdrip # Make sure no screeners or cams are downloaded
    list_match:
      from:
        - movie_list: pelidescarga
    transmission:
      host: 192.168.1.38
      port: 9091
      username: gacomun
      password: JcO45101814
  remove_stale_torrents:
    from_transmission:
      host: 192.168.1.38
      port: 9091
      username: gacomun
      password: JcO45101814
    disable: [seen, seen_info_hash]
    if:
      - transmission_progress == 100: accept
      - not transmission_seed_ratio_ok: reject
      - not transmission_idle_limit_ok: reject
    transmission:
      host: 192.168.1.38
      port: 9091
      username: gacomun
      password: JcO45101814
      action: purge